apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-aws.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hello-aws.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
  selector:
    {{- include "hello-aws.selectorLabels" . | nindent 4 }}
